### ISSUE TITLE
Order total shipment weight

### ISSUE THREAD

**Issue by simbus82** [mage-eag/mage-enhanced-admin-grids#138]
Is it possible to show in orders page a column with the order total weight? Thanks!

**Comment by simbus82** [comment]
Oh yes, is the right value for total weight of an order! Nice!

**Comment by simbus82** [comment]
Bump ;-) it could be a very useful enhancement. I'm so sorry thant i'm not so good in develop, i love your grid extension! I can only... try and speak!

**Comment by mage-eag** [comment]
Sorry for the delay ! just have added the column on the :
- 0.9.0 branch (4497568b33157794a23c541062c9a34bb4b3c99d)
- 1.0.0-wip branch (630d433e2676bac545552734f9e92ac5563ef81e)

If you are currently using the 1.0.0-wip branch, you may want to temporarily copy the corresponding changes instead of updating everything (especially if this is an "old" version), because the latest commits brought a lot of changes that may still be unstable.
