### ISSUE TITLE
Wildcard for custom filter

### ISSUE THREAD

**Issue by Maikel-Koek** [mage-eag/mage-enhanced-admin-grids#157]
Hi,

We updated the module to version 1.0.0 for one of our clients, who used the column 'sales_order/custom_items' to search on product SKUs in orders.

Before, they could search on for example '001' to find 'product-001', but this doesn't work anymore, the only way orders with product-001 can be found is to completely enter 'product-001'.

Is it possible to filter with a wildcard? If so, how?

Thanks

**Comment by Khian** [comment]
I have the same problem. Have you found a solution??

Thanks!

**Comment by Maikel-Koek** [comment]
No solution yet, I'm still awaiting the answer of @mage-eag ..

**Comment by Khian** [comment]
I do not think we will get response. I'm checking the code and I know what and where is the issue. But I'm still looking for a solution. I'll post it here when I found it

**Comment by Khian** [comment]
I found a solution. on: /app/code/community/BL/CustomGrid/Block/Widget/Grid/Column/Filter
You have to modify the Text.php replacing all to this:
<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   BL
 * @package    BL_CustomGrid
 * @copyright  Copyright (c) 2014 Benoît Leulliette <benoit.leulliette@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

class BL_CustomGrid_Block_Widget_Grid_Column_Filter_Text extends Mage_Adminhtml_Block_Widget_Grid_Column_Filter_Text
{
    public function getHtml()
    {
        $html = '<div class="field-100"><input type="text" name="'.$this->_getHtmlName().'" id="'.$this->_getHtmlId().'" value="'.$this->getEscapedValue().'" class="input-text no-changes"/></div>';
        return $html;
    }
}

**Comment by mage-eag** [comment]
Sorry for the really late answer, I've literally been swamped with work for the last three months or so, and wanted to complete the next big commit before catching up with all the new questions and issues (kind of underestimated both).

Starting from 6afd05aeed56a01f5a3070d848fa68e05b5458a8, the items filter will again be applied as an "inside like" rather than an "exact like".
Also, I'm planning to investigate whether it's possible to allow customizing the filtering just as for the other columns using the "Text" renderer (but without the rendering part).
