### ISSUE TITLE
wip 1.0.0 install error

### ISSUE THREAD

**Issue by Veiote** [mage-eag/mage-enhanced-admin-grids#181]
I tried install last wip 1.0.0 in magento 1.9 and got this error:

PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'max_attribute_column_id' in 'customgrid_grid' in C:\www\magento\lib\Zend\Db\Statement\Pdo.php on line 228
C:\www\magento\app\code\community\BL\CustomGrid\sql\customgrid_setup\mysql4-upgrade-0.8.4.4-0.8.9.php

Also tried 0.8.9 and 0.9.0

only SQL tables were created:
customgrid_grid_profile
customgrid_grid_role
customgrid_grid_user

**Comment by mage-eag** [comment]
Seems that update scripts were not run in the correct order, or that a race condition occurred because the extension setup was run twice almost simultaneously.

Can you drop the extension tables, delete the `customgrid_setup` row in the `core_resource` table, and try to install the extension again, but ensuring that the setup is only triggered once (only load one page at once as long as the setup has not been triggered and completed) ?

If the problem still occurs, I'll try to debug the setup on Windows, and maybe create a full install script for the new 1.0.0 version (could be preferable to running a bunch of update scripts, while being a convenient work-around for that kind of install problem).

**Comment by Veiote** [comment]
I tested in a fresh instalation and it's working.

Thanks

**Comment by seansan** [comment]
May also be other issue where is reported that the installer does not run (but rather first the observer)
