### ISSUE TITLE
EAG error : The "Customizable" custom column could not be applied : "The block is not valid"

### ISSUE THREAD

**Issue by dibyajyotimallick** [mage-eag/mage-enhanced-admin-grids#187]
Hi,
I am using Magento EE.

Everytime i try to add a custom column in the order page, i get EAG error - "The block is not valid".
 How can i troubleshoot this?

Thanks

**Comment by mage-eag** [comment]
This error means that the orders grid is being rewrited by another extension, with which the custom column may not be compatible. This check was added as a precautionary measure, but because it was too blocking (and probably not that useful in a majority of cases), it is possible to turn it off starting from version 1.0.0 (wip).

If you do not want to use the wip version (quite advanced but still unstable), you can disable the check by making `BL_CustomGrid_Model_Custom_Column_Abstract::verifyBlock()` always return true.

**Comment by epiblue** [comment]
@mage-eag 

Hello, could you please indicate in witch file this filter line can be found? 

And also, we see on Magento connect theres only 0.9.2 version available, where can we find more info about the new version? 

Thank you,
