### ISSUE TITLE
Custom Columns

### ISSUE THREAD

**Issue by homerjsim** [mage-eag/mage-enhanced-admin-grids#189]
Hello,

I'm using the following extension www.magentocommerce.com/magento-connect/customer-credits.html
and I want to display some informations in the order grid. I know how to get the needed values programtically, e.g. $_order->getCustomerCreditAmount()
How do I add this as a column in the order grid?

Best Regards
Stefan

**Comment by mage-eag** [comment]
Can you tell on which table the field is located ? You will at least need to create an `etc/customgrid.xml` config file in order to hold the custom column definition inside the `sales_order` grid type, then depending on the location of the field, it may be possible to use a base class requiring only a few configuration values to work.

**Comment by homerjsim** [comment]
Sorry for the delayed answer. I solved that one myself
I included this in the customgrid.xml

<credit model="customgrid/custom_column_order_base" module="customgrid">
                    <name>Credit</name>
                    <allow_renderers>1</allow_renderers>
                    <config_params>
                        <order_field_name>customer_credit_amount</order_field_name>
                    </config_params>
 </credit>

**Comment by mage-eag** [comment]
Perfect, that is the best solution for your need :)
