### ISSUE TITLE
Admin pages slow because of custom grid extension enabled

### ISSUE THREAD

**Issue by tony-dtn** [mage-eag/mage-enhanced-admin-grids#193]
I have one magento CE setup and has BL_CustomGrid installed for almost 2 years. Admin UI has been slowed down significantly in the last few months. After enabled profiler, I found that BL_CustomGrid_Model_Observer.onControllerActionPreDispatch takes 20 seconds, sometimes 40 seconds. Logging in more detail, I see that this command:
$this->_gridsCollection = Mage::getResourceModel('customgrid/grid_collection')
            ->addFieldToFilter('module_name', $this->getModuleName())
            ->addFieldToFilter('controller_name', $this->getControllerName())
            ->load();
takes 90% of time (so 20 or 40 seconds).
Checking in db, I see customgrid_grid has 6000 records and customgrid_grid_column has 49000 records. 
If I get the sql from $this->_gridsCollection and run in phpmyadmin, it just takes less than 1 second. I am investigating why the  collection.load takes so much time.
Any help is much appreciated.

Thank you

**Comment by mage-eag** [comment]
I can see at least two things that could cause the grids slowdown :

1. having 6000 records in `customgrid_grid` is not "normal". It is certainly due to some grid blocks with dynamic IDs, which previous versions of the extension detected as new grids each time they were loaded, leading to more and more doublons being created. As this has only been completely fixed starting with version 1.0.0 (still wip), a temporary solution prior to that is to register exclusions for each concerned block type in the system configuration. In your case, I would suggest you to :
  - use this query to find all the concerned block types : `SELECT DISTINCT block_type FROM customgrid_grid WHERE block_id REGEXP "([0-9a-f]){32}"`,
  - register the corresponding exclusions,
  - delete all the corresponding grids : `DELETE FROM customgrid_grid WHERE block_id REGEXP "([0-9a-f]){32}"`.

2. correlated to the first point, versions prior to 1.0.0 were applying the same pre-loading treatments for grid models loaded independtly or from within a collection, what was not optimized at all for the latter case. While it had not much of an impact when only a few grids were concerned, the loading time increased linearly with the number of loaded grids. After having cleaned up the `customgrid_grid` table things should go better again, but tell me if that would not be the case, so that we can investigate further :)

**Comment by tony-dtn** [comment]
Hi,
You are correct, I found these blocks have dynamic IDs: amaudit/adminhtml_tabs_order and amaudit/adminhtml_tabs_product
And I have deleted those records as well as added them to exception. 

This solved the issue.

Thank you and looking forward to the 1.0 version.

**Comment by alexbogias** [comment]
Thanks a lot @mage-eag
